### ISSUE TITLE
Move to Bulma 1.0

### ISSUE THREAD

**Issue by RomainMendez** [michael-hack/bulma-calendar#337]
**Is your feature request related to a problem? Please describe.**
This project in NPM forces dependencies on bulma 0.9.4

**Describe the solution you'd like**
Move the same package and neat visuals to bulma 1.0

**Describe alternatives you've considered**
Forcing NPM installs, but this is a scary solution.

**Comment by natkuu** [comment]
Having the same issue trying to install the package. Please fix 🙏

**Comment by Curs3W4ll** [comment]
Same here

**Comment by michael-hack** [comment]
Done with 7.1.1
